from stl import mesh

your_mesh = mesh.Mesh.from_file('base_link1.STL')
your_mesh.save('base_link.STL')
your_mesh = mesh.Mesh.from_file('gripper_base1.STL')
your_mesh.save('gripper_base.STL')
your_mesh = mesh.Mesh.from_file('link11.STL')
your_mesh.save('link1.STL')
your_mesh = mesh.Mesh.from_file('link21.STL')
your_mesh.save('link2.STL')
your_mesh = mesh.Mesh.from_file('link31.STL')
your_mesh.save('link3.STL')
your_mesh = mesh.Mesh.from_file('link41.STL')
your_mesh.save('link4.STL')
your_mesh = mesh.Mesh.from_file('link51.STL')
your_mesh.save('link5.STL')
your_mesh = mesh.Mesh.from_file('link61.STL')
your_mesh.save('link6.STL')
your_mesh = mesh.Mesh.from_file('link71.STL')
your_mesh.save('link7.STL')
your_mesh = mesh.Mesh.from_file('link81.STL')
your_mesh.save('link8.STL')